"""Trading domain helpers — XAUUSD-only platform."""

from app.domain.trading.gold_only import (
    AUTONOMOUS_DISPLAY_NAME,
    CANONICAL_GOLD_BROKER_DISPLAY,
    DISABLED_AUTONOMOUS_SYMBOL,
    GOLD_SYMBOL,
    DisabledAutonomousSymbolError,
    autonomous_execution_symbols,
    default_trading_symbol,
    filter_gold_symbols,
    gold_only_diagnostics,
    gold_only_enabled,
    is_autonomous_execution_symbol,
    is_gold_symbol,
    require_xauusd,
    resolve_trading_symbol,
    same_gold_identity,
    symbol_in_scan_universe,
)
from app.domain.trading.xauusd_specs import (
    CONTRACT_SIZE,
    MAX_LEVERAGE,
    MAX_SPREAD,
    SYMBOL,
    coerce_max_spread,
    exposure_pct_of_equity,
    margin_required,
    notional_value,
    specs_dict,
)

__all__ = [
    "AUTONOMOUS_DISPLAY_NAME",
    "CANONICAL_GOLD_BROKER_DISPLAY",
    "DISABLED_AUTONOMOUS_SYMBOL",
    "DisabledAutonomousSymbolError",
    "CONTRACT_SIZE",
    "GOLD_SYMBOL",
    "MAX_LEVERAGE",
    "MAX_SPREAD",
    "SYMBOL",
    "autonomous_execution_symbols",
    "coerce_max_spread",
    "default_trading_symbol",
    "exposure_pct_of_equity",
    "filter_gold_symbols",
    "gold_only_diagnostics",
    "gold_only_enabled",
    "is_autonomous_execution_symbol",
    "is_gold_symbol",
    "margin_required",
    "notional_value",
    "require_xauusd",
    "resolve_trading_symbol",
    "same_gold_identity",
    "symbol_in_scan_universe",
    "specs_dict",
]
