"""HTTP API routers."""

from app.presentation.routers import (
    auth,
    backtest,
    broker_accounts,
    broker_connections,
    brokers,
    execution,
    health,
    mt5,
    notifications,
    ops,
    organizations,
    paper,
    portfolio,
    profile,
    risk,
    settings,
    strategy,
    version,
    walkforward,
    intelligence,
)

__all__ = [
    "auth",
    "backtest",
    "broker_accounts",
    "broker_connections",
    "brokers",
    "execution",
    "health",
    "intelligence",
    "mt5",
    "notifications",
    "ops",
    "organizations",
    "paper",
    "portfolio",
    "profile",
    "risk",
    "settings",
    "strategy",
    "version",
    "walkforward",
]
