"use client";

import { PageHeader } from "@/components/layout/page-header";
import { PageMotion } from "@/components/desk/motion";
import { AqsReportsWorkspace } from "@/components/ops/aqs-workspaces";

export default function AqsReportsPage() {
  return (
    <div>
      <PageHeader title="AQS Executive Reports" description="Institutional research reports generated by AQS." />
      <PageMotion>
        <AqsReportsWorkspace />
      </PageMotion>
    </div>
  );
}
